namespace PortalExcursiones.Infraestructura.Enumeraciones
{
    public enum Codigos
    {
        OK = 1,
        ERROR_DE_VALIDACION = 2,
        ERROR_DE_SERVIDOR = 3,
        REGISTRO_NO_ENCONTRADO = 4,
        NO_AUTENTICADO = 5,
        ERROR_RESETEANDO_PASSWORD = 6,
        ERROR_CAMBIO_PASSWORD = 7,
        ERROR_EXISTEN_FECHAS_REPETIDAS = 8,
        ELIMINACION_NO_EFECTUADA = 9,
        REGISTRO_REPETIDO = 10,
        CONTENT_TYPE_NO_CORRECTO = 11,
        NUMERO_DE_PLAZAS_INSUFICIENTE = 12,
        MINIMO_DE_PERSONAS_INSUFICIENTE = 13,
        PRECIO_NO_ENCONTRADO = 14,
        ERROR_PASARELA_PAGO = 15,
        ERROR_CODIGO_IDIOMA_INCORRECTO = 16,
        SERVICIO_RECOGIDA_NO_SOPORTADO = 17,
        ERROR_AÑADIENDO_ROL = 18,
        ERROR_OPERACION_NO_PERMITIDA = 19
    }
}