// <auto-generated />
namespace CapaDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtable_puntoregocida_exact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtable_puntoregocida_exact));
        
        string IMigrationMetadata.Id
        {
            get { return "201612191758165_addtable_puntoregocida_exact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
