// <auto-generated />
namespace CapaDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modify_table_idioma_guia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_table_idioma_guia));
        
        string IMigrationMetadata.Id
        {
            get { return "201612171812489_modify_table_idioma_guia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
