// <auto-generated />
namespace CapaDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_fields_preciotemporada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_fields_preciotemporada));
        
        string IMigrationMetadata.Id
        {
            get { return "201612261947259_new_fields_preciotemporada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
