// <auto-generated />
namespace CapaDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletetable_calendarioex_puntorecogida : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletetable_calendarioex_puntorecogida));
        
        string IMigrationMetadata.Id
        {
            get { return "201612191628006_deletetable_calendarioex_puntorecogida"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
