// <auto-generated />
namespace CapaDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newfield_motivoanulacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newfield_motivoanulacion));
        
        string IMigrationMetadata.Id
        {
            get { return "201701102350567_newfield_motivoanulacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
