// <auto-generated />
namespace CapaDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_table_clave_valor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_table_clave_valor));
        
        string IMigrationMetadata.Id
        {
            get { return "201701080123460_new_table_clave_valor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
