// <auto-generated />
namespace CapaDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_field_proveedor_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_field_proveedor_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201701041501096_new_field_proveedor_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
