//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErroresValidacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErroresValidacion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaDatos.Properties.ErroresValidacion", typeof(ErroresValidacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario con id {0} no existe.
        /// </summary>
        public static string error1 {
            get {
                return ResourceManager.GetString("error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo nombre es requerido.
        /// </summary>
        public static string error10 {
            get {
                return ResourceManager.GetString("error10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo primerapellido es requerido.
        /// </summary>
        public static string error11 {
            get {
                return ResourceManager.GetString("error11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo segundoapellido es requerido.
        /// </summary>
        public static string error12 {
            get {
                return ResourceManager.GetString("error12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo direccion1 es requerido.
        /// </summary>
        public static string error13 {
            get {
                return ResourceManager.GetString("error13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo localidad es requerido.
        /// </summary>
        public static string error14 {
            get {
                return ResourceManager.GetString("error14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo número de identificación es requerido.
        /// </summary>
        public static string error15 {
            get {
                return ResourceManager.GetString("error15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario {0} ya existe,por favor,elija otro diferente.
        /// </summary>
        public static string error16 {
            get {
                return ResourceManager.GetString("error16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de correo {0} ya existe,por favor,elija otra diferente.
        /// </summary>
        public static string error17 {
            get {
                return ResourceManager.GetString("error17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo nombre de empresa es requerido.
        /// </summary>
        public static string error18 {
            get {
                return ResourceManager.GetString("error18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo cif es requerido.
        /// </summary>
        public static string error19 {
            get {
                return ResourceManager.GetString("error19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo id es requerido.
        /// </summary>
        public static string error2 {
            get {
                return ResourceManager.GetString("error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo latitud es requerido.
        /// </summary>
        public static string error20 {
            get {
                return ResourceManager.GetString("error20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo longitud es requerido.
        /// </summary>
        public static string error21 {
            get {
                return ResourceManager.GetString("error21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI o NIE es incorrecto.
        /// </summary>
        public static string error22 {
            get {
                return ResourceManager.GetString("error22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El CIF es incorrecto, revise que no hayan guiones.
        /// </summary>
        public static string error23 {
            get {
                return ResourceManager.GetString("error23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo email es requerido.
        /// </summary>
        public static string error3 {
            get {
                return ResourceManager.GetString("error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de email no es válida.
        /// </summary>
        public static string error4 {
            get {
                return ResourceManager.GetString("error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo usuario es requerido.
        /// </summary>
        public static string error5 {
            get {
                return ResourceManager.GetString("error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo usuario no es válido, asegúrese de que introduce al menos seis o mas caractéres alfanuméricos.
        /// </summary>
        public static string error6 {
            get {
                return ResourceManager.GetString("error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo password es requerido.
        /// </summary>
        public static string error7 {
            get {
                return ResourceManager.GetString("error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo password no es válido, asegúrese de que introduce al menos seis o mas caractéres alfanuméricos.
        /// </summary>
        public static string error8 {
            get {
                return ResourceManager.GetString("error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo teléfono es requerido.
        /// </summary>
        public static string error9 {
            get {
                return ResourceManager.GetString("error9", resourceCulture);
            }
        }
    }
}
