//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalExcursiones.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalExcursiones.Properties.Errores", typeof(Errores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario con ID {0} no se ha podido encontrar.
        /// </summary>
        public static string error1 {
            get {
                return ResourceManager.GetString("error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe una configuración con el mismo nombre.
        /// </summary>
        public static string error10 {
            get {
                return ResourceManager.GetString("error10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha nueva desde ser mayo que la fecha actual.
        /// </summary>
        public static string error11 {
            get {
                return ResourceManager.GetString("error11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El periodo de fechas coincide en parte o completamente con otro periodo..
        /// </summary>
        public static string error12 {
            get {
                return ResourceManager.GetString("error12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha desde tiene que ser menor que la fecha hasta.
        /// </summary>
        public static string error13 {
            get {
                return ResourceManager.GetString("error13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado ninguna excursion que coincida con la fecha/hora seleccionada.
        /// </summary>
        public static string error14 {
            get {
                return ResourceManager.GetString("error14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Únicamente quedan {0} plaza/as. Disminuya el número de personas.
        /// </summary>
        public static string error15 {
            get {
                return ResourceManager.GetString("error15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado ningún precio configurado para dicha excursión/actividad.
        /// </summary>
        public static string error17 {
            get {
                return ResourceManager.GetString("error17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un error tramitando el pago, por favor, inténtelo de nuevo.
        /// </summary>
        public static string error18 {
            get {
                return ResourceManager.GetString("error18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No quedan plazas disponibles para la fecha seleccionada, por favor, elija otra.
        /// </summary>
        public static string error19 {
            get {
                return ResourceManager.GetString("error19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado a ningún usuario con las credenciales proporcionadas.
        /// </summary>
        public static string error2 {
            get {
                return ResourceManager.GetString("error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe un registro con el mismo nombre, por favor, elija otro nombre.
        /// </summary>
        public static string error20 {
            get {
                return ResourceManager.GetString("error20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El punto de recogida enviado en la reserva no existe o no pertenece a dicha configuración.
        /// </summary>
        public static string error21 {
            get {
                return ResourceManager.GetString("error21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha desde tiene que ser mayor que la fecha actual.
        /// </summary>
        public static string error22 {
            get {
                return ResourceManager.GetString("error22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha que se está bsucando tiene que ser mayor que la fecha actual.
        /// </summary>
        public static string error23 {
            get {
                return ResourceManager.GetString("error23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La excursión actividad no soporta servicio de recogida, no es posible configurar puntos de recogida.
        /// </summary>
        public static string error24 {
            get {
                return ResourceManager.GetString("error24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene que enviar 5 nombres,uno para cada genero y deben ser:[ adulto | niño | infante | junior | senior ].
        /// </summary>
        public static string error25 {
            get {
                return ResourceManager.GetString("error25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ya está confogurado para la excursion/actividad.
        /// </summary>
        public static string error26 {
            get {
                return ResourceManager.GetString("error26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene que enviar un nombre de genero el cual debe pertenecer a este conjunto: [ adulto | niño | infante | junior | senior ].
        /// </summary>
        public static string error27 {
            get {
                return ResourceManager.GetString("error27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene que enviar un tipo de duracion el cual debe pertenecer a este conjunto: [ dia| hora | minuto | flexible ].
        /// </summary>
        public static string error28 {
            get {
                return ResourceManager.GetString("error28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si el tipo de duración es flexible, el valor de la duración ha de ser mayor que cero.
        /// </summary>
        public static string error29 {
            get {
                return ResourceManager.GetString("error29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no tenia la sesión iniciada, no es posible realizar un logout.
        /// </summary>
        public static string error3 {
            get {
                return ResourceManager.GetString("error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se tiene que reservar al menos una plaza.
        /// </summary>
        public static string error30 {
            get {
                return ResourceManager.GetString("error30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo costegrupo es requerido.
        /// </summary>
        public static string error31 {
            get {
                return ResourceManager.GetString("error31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al contabilizarse los infantes, es necesario especificar el coste.
        /// </summary>
        public static string error32 {
            get {
                return ResourceManager.GetString("error32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo motivo de anulación es requerido.
        /// </summary>
        public static string error33 {
            get {
                return ResourceManager.GetString("error33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe ningún usuario con la direccion de email proporcionada.
        /// </summary>
        public static string error4 {
            get {
                return ResourceManager.GetString("error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de email proporcionada es incorrecta.
        /// </summary>
        public static string error5 {
            get {
                return ResourceManager.GetString("error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe ningún registro con el ID proporcionado.
        /// </summary>
        public static string error6 {
            get {
                return ResourceManager.GetString("error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor de la fecha hasta es menor o igual que el valor de la fecha desde.
        /// </summary>
        public static string error7 {
            get {
                return ResourceManager.GetString("error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe una reserva,un punto de recogida o un guia asociado a dicha fecha, la eliminación no es posible.
        /// </summary>
        public static string error8 {
            get {
                return ResourceManager.GetString("error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La excursion/actividad ya tiene asignada la fecha proporcionada, no es posible modificarla.
        /// </summary>
        public static string error9 {
            get {
                return ResourceManager.GetString("error9", resourceCulture);
            }
        }
    }
}
