//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalExcursiones.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalExcursiones.Properties.Errores", typeof(Errores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario con ID {0} no se ha podido encontrar.
        /// </summary>
        public static string error1 {
            get {
                return ResourceManager.GetString("error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe una configuración con el mismo nombre.
        /// </summary>
        public static string error10 {
            get {
                return ResourceManager.GetString("error10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha nueva desde ser mayo que la fecha actual.
        /// </summary>
        public static string error11 {
            get {
                return ResourceManager.GetString("error11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El periodo de fechas coincide en parte o completamente con otro periodo..
        /// </summary>
        public static string error12 {
            get {
                return ResourceManager.GetString("error12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha desde tiene que ser menor que la fecha hasta.
        /// </summary>
        public static string error13 {
            get {
                return ResourceManager.GetString("error13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado a ningún usuario con las credenciales proporcionadas.
        /// </summary>
        public static string error2 {
            get {
                return ResourceManager.GetString("error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no tenia la sesión iniciada, no es posible realizar un logout.
        /// </summary>
        public static string error3 {
            get {
                return ResourceManager.GetString("error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe ningún usuario con la direccion de email proporcionada.
        /// </summary>
        public static string error4 {
            get {
                return ResourceManager.GetString("error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección de email proporcionada es incorrecta.
        /// </summary>
        public static string error5 {
            get {
                return ResourceManager.GetString("error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe ningún registro con el ID proporcionado.
        /// </summary>
        public static string error6 {
            get {
                return ResourceManager.GetString("error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del campo hasta es menor que el valor del campo desde.
        /// </summary>
        public static string error7 {
            get {
                return ResourceManager.GetString("error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe una reserva,un punto de recogida o un guia asociado a dicha fecha, la eliminación no es posible.
        /// </summary>
        public static string error8 {
            get {
                return ResourceManager.GetString("error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La excursion/actividad ya tiene asignada la fecha proporcionada, no es posible modificarla.
        /// </summary>
        public static string error9 {
            get {
                return ResourceManager.GetString("error9", resourceCulture);
            }
        }
    }
}
