//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalExcursiones.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErroresValidacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErroresValidacion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalExcursiones.Properties.ErroresValidacion", typeof(ErroresValidacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo password anterior es requerido.
        /// </summary>
        public static string error1 {
            get {
                return ResourceManager.GetString("error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno de los dias enviados no se corresponde a un día de la semana.
        /// </summary>
        public static string error10 {
            get {
                return ResourceManager.GetString("error10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene que enviar al menos un horario.
        /// </summary>
        public static string error11 {
            get {
                return ResourceManager.GetString("error11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno de los horarios enviados tiene un formato incorrecto..
        /// </summary>
        public static string error12 {
            get {
                return ResourceManager.GetString("error12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo fecha desde es requerido.
        /// </summary>
        public static string error13 {
            get {
                return ResourceManager.GetString("error13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo fecha hasta es requerido.
        /// </summary>
        public static string error14 {
            get {
                return ResourceManager.GetString("error14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo horarios es requerido.
        /// </summary>
        public static string error15 {
            get {
                return ResourceManager.GetString("error15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo dias es requerido.
        /// </summary>
        public static string error16 {
            get {
                return ResourceManager.GetString("error16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo ID es obligatorio.
        /// </summary>
        public static string error17 {
            get {
                return ResourceManager.GetString("error17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere especificar la categoría a la que pertence la activad/excursión.
        /// </summary>
        public static string error18 {
            get {
                return ResourceManager.GetString("error18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede enviar al mismo tiempo los campos tipoexcursion y tipoactividad.
        /// </summary>
        public static string error19 {
            get {
                return ResourceManager.GetString("error19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo password anterior no es válido, asegúrese de que introduce al menos seis o mas caractéres alfanuméricos.
        /// </summary>
        public static string error2 {
            get {
                return ResourceManager.GetString("error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo tipoexcursion es requerido.
        /// </summary>
        public static string error20 {
            get {
                return ResourceManager.GetString("error20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo tipoactividad es requerido.
        /// </summary>
        public static string error21 {
            get {
                return ResourceManager.GetString("error21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo nombre es requerido.
        /// </summary>
        public static string error24 {
            get {
                return ResourceManager.GetString("error24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo latitud es requerido.
        /// </summary>
        public static string error25 {
            get {
                return ResourceManager.GetString("error25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo longitud es requerido.
        /// </summary>
        public static string error26 {
            get {
                return ResourceManager.GetString("error26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo direccion es requerido.
        /// </summary>
        public static string error27 {
            get {
                return ResourceManager.GetString("error27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo fecha es requerido.
        /// </summary>
        public static string error28 {
            get {
                return ResourceManager.GetString("error28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo fecha nueva es requerido.
        /// </summary>
        public static string error29 {
            get {
                return ResourceManager.GetString("error29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo password nuevo es requerido.
        /// </summary>
        public static string error3 {
            get {
                return ResourceManager.GetString("error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo username es requerido.
        /// </summary>
        public static string error30 {
            get {
                return ResourceManager.GetString("error30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La confirmación del password no coincide.
        /// </summary>
        public static string error31 {
            get {
                return ResourceManager.GetString("error31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo confirmación password no es válido, asegúrese de que introduce al menos seis o mas caractéres alfanuméricos.
        /// </summary>
        public static string error32 {
            get {
                return ResourceManager.GetString("error32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo confirmación password es requerido.
        /// </summary>
        public static string error33 {
            get {
                return ResourceManager.GetString("error33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo password nuevo no es válido, asegúrese de que introduce al menos seis o mas caractéres alfanuméricos.
        /// </summary>
        public static string error4 {
            get {
                return ResourceManager.GetString("error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo userid es requerido.
        /// </summary>
        public static string error5 {
            get {
                return ResourceManager.GetString("error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo token es requerido.
        /// </summary>
        public static string error6 {
            get {
                return ResourceManager.GetString("error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo password es requerido.
        /// </summary>
        public static string error7 {
            get {
                return ResourceManager.GetString("error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo password no es válido, asegúrese de que introduce al menos seis o mas caractéres alfanuméricos.
        /// </summary>
        public static string error8 {
            get {
                return ResourceManager.GetString("error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene que enviar al menos un dia de la semana.
        /// </summary>
        public static string error9 {
            get {
                return ResourceManager.GetString("error9", resourceCulture);
            }
        }
    }
}
